version: '3'
services:
  nginx:
    container_name: nginx-container
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./nginx/volumes:/usr/share/nginx
  #datascience-notebook:
  #  container_name: datascience-notebook-container
  #  build:
  #    context: .
  #    dockerfile: ./datascience-notebook/Dockerfile
  #  ports:
  #    - 8081:8888  
  #  volumes:
  #    - ./datascience-notebook/volumes:/home/jovyan/work
  jupyterlab:
    restart: always
    container_name: jupyterlab-container
    #environment:
    #  - JUPYTER_ENABLE_LAB=yes
    #  - AWS_ACCESS_KEY_ID=AKIXXXXXXXXXXXXXXXXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    build:
      context: jupyterlab
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./jupyterlab/root:/root/.jupyter
      - ./jupyterlab/workspace:/workspace
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
  cellrank:
    restart: always
    container_name: cellrank-container
    build:
      context: jupyterlab-cellrank
      dockerfile: ./Dockerfile
    ports:
      - 8889:8888
    volumes:
      - ./jupyterlab-cellrank/root:/root/.jupyter
      - ./jupyterlab-cellrank/workspace:/workspace
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace