version: '3'
services:
  web:
    build:
      context: flask-redis
      dockerfile: ./Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./$flaskredisdir/code:/code
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"